
theme = "nightfox"
# nightfox is the goat

[editor]
continue-comments = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'"' = '"'
# need to exclude single pairs string for the f-string bind...
'<' = '>'
'(' = ')'
'[' = ']'
'{' = '}'

[editor.indent-guides]
render = true
character = "|"

[keys.normal]
j = "move_line_up"
k = "move_line_down"
C-j = "page_cursor_half_up"
C-k = "page_cursor_half_down"

[keys.normal.space.w]
j = "jump_view_up"
k = "jump_view_down"

[keys.normal.space.q] # custom menu?
# this is for replacing 'PySide2' with 'PyQt5' when using qt designer
w = "@%d<space>P%sPySide2<ret><esc>d"
# for quickly creating a python f-string. issues/4035 my goat.
e = "@if''<esc>hi"

[keys.select]
j = "extend_line_up"
k = "extend_line_down"
